In [1]:
import pandas as pd
import numpy as np
from my_functions import read_large_csv_parallel
import datetime 
import os
from tqdm import tqdm
from utils import utils

In [2]:
his_path = 'D:/量化实习/zorro/回测数据/A股天数据'
for index in [1000,800,500]:
    index_path = f'D:/量化实习/zorro/回测数据/中证{index}成分股'
    save_path = f'config/中证{index}'
    if not os.path.exists(save_path):
        os.makedirs(save_path)
    df = utils.get_his_data(his_path=his_path,index_path=index_path,save_path=save_path)

程序运行时间： 6.999164819717407 秒
程序运行时间： 0.7898623943328857 秒

100%|██████████| 108/108 [01:35<00:00,  1.13it/s]
d:\量化实习\量化课\utils\utils.py:53: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  expanded_df = pd.concat([expanded_df, index_combo[index_combo['trade_date'] == unique_dates[-1]]],

程序运行时间： 6.819057941436768 秒
程序运行时间： 0.823998212814331 秒

100%|██████████| 233/233 [03:49<00:00,  1.02it/s]
d:\量化实习\量化课\utils\utils.py:53: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  expanded_df = pd.concat([expanded_df, index_combo[index_combo['trade_date'] == unique_dates[-1]]],

程序运行时间： 6.610612869262695 秒
程序运行时间： 0.8233768939971924 秒

100%|██████████| 257/257 [02:36<00:00,  1.65it/s]
d:\量化实习\量化课\utils\utils.py:53: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  expanded_df = pd.concat([expanded_df, index_combo[index_combo['trade_date'] == unique_dates[-1]]],

In [13]:
df['future_1d_ret'].idxmax()

582318

In [15]:
df

,index_code,token,date,weight,open,high,low,close,pre_close,change,...,amount,future_1d_ret,future_7d_ret,future_20d_ret,future_1d_ret_rank,future_1d_ret_cat,future_7d_ret_rank,future_7d_ret_cat,future_20d_ret_rank,future_20d_ret_cat
0,000905.SH,000006.SZ,2007-01-31,0.470,12.88,12.88,11.89,11.93,12.90,-0.97,...,150065.6750,0.010897,-0.009220,0.141660,0.565401,1,0.100823,0,0.303279,0
1,000905.SH,000016.SZ,2007-01-31,0.240,5.16,5.16,4.80,4.84,5.14,-0.30,...,40989.5544,0.020661,0.057851,0.167355,0.689873,2,0.438272,1,0.372951,1
2,000905.SH,000028.SZ,2007-01-31,0.140,9.61,9.89,8.90,9.44,9.89,-0.45,...,26694.6612,-0.016949,0.037076,0.036017,0.183544,0,0.316872,0,0.100410,0
3,000905.SH,000032.SZ,2007-01-31,0.090,6.16,6.30,5.75,5.84,6.13,-0.29,...,35071.5780,0.061644,0.073630,0.226027,0.919831,2,0.563786,1,0.555328,1
4,000905.SH,000033.SZ,2007-01-31,0.080,4.05,4.15,3.87,3.87,4.16,-0.29,...,46560.4690,0.100775,0.131783,0.263566,0.993671,2,0.816872,2,0.663934,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2004928,000905.SH,688772.SH,2024-04-23,0.146,12.00,12.10,11.45,11.73,12.28,-0.55,...,283071.5440,0.005968,0.110827,0.199488,0.477612,1,0.806061,2,0.965092,2
2004929,000905.SH,688778.SH,2024-04-23,0.087,32.46,33.13,32.46,32.66,32.71,-0.05,...,62880.1410,-0.017146,0.126454,0.065830,0.093817,0,0.866667,2,0.770021,2
2004930,000905.SH,688779.SH,2024-04-23,0.083,4.96,5.03,4.92,4.93,4.92,0.01,...,74533.5660,-0.010142,0.162272,0.050710,0.166311,0,0.951515,2,0.702259,2
2004931,000905.SH,688819.SH,2024-04-23,0.062,30.12,30.32,28.81,29.05,30.11,-1.06,...,94991.8070,-0.005508,0.023064,-0.086059,0.230277,0,0.240404,0,0.090349,0
2004932,000905.SH,689009.SH,2024-04-23,0.208,30.76,31.88,30.21,31.34,30.36,0.98,...,292008.0660,0.014997,0.167198,0.260370,0.671642,2,0.955556,2,0.983573,2

In [21]:
df[(df['token'] == '000733.SZ')].to_csv('a.csv')

In [16]:
df.iloc[582318,:]

index_code              000905.SH
token                   000733.SZ
date                   2012-01-30
weight                       0.11
open                         6.37
high                         6.44
low                          6.25
close                        6.26
pre_close                    6.37
change                      -0.11
pct_chg                     -1.73
vol                      15563.48
amount                  9859.9694
future_1d_ret           18.853035
future_7d_ret           16.902556
future_20d_ret          16.900958
future_1d_ret_rank            1.0
future_1d_ret_cat               2
future_7d_ret_rank            1.0
future_7d_ret_cat               2
future_20d_ret_rank           1.0
future_20d_ret_cat              2
Name: 582318, dtype: object

In [2]:
his_df = read_large_csv_parallel('D:/量化实习/zorro/回测数据/A股天数据')
index_combo = read_large_csv_parallel('D:/量化实习/zorro/回测数据/中证800成分股')

程序运行时间： 8.105883121490479 秒
程序运行时间： 1.373842716217041 秒

In [30]:
zz_800 = utils.get_index_combo(his_df=his_df,index_combo=index_combo)

100%|██████████| 233/233 [04:07<00:00,  1.06s/it]
d:\量化实习\量化课\utils\utils.py:53: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  expanded_df = pd.concat([expanded_df, index_combo[index_combo['trade_date'] == unique_dates[-1]]],

In [32]:
zz_800.dropna(inplace=True)

In [33]:
zz_800

,index_code,ts_code,trade_date,weight,open,high,low,close,pre_close,change,pct_chg,vol,amount
1,000906.SH,600021.SH,2007-04-20,0.100,8.56,9.39,8.56,9.29,9.05,0.24,2.6500,336658.91,305546.714
2,000906.SH,600790.SH,2007-04-20,0.100,12.04,12.50,12.04,12.41,11.86,0.55,4.6400,229734.69,282144.245
4,000906.SH,600151.SH,2007-04-20,0.100,14.44,15.10,14.43,14.88,14.33,0.55,3.8400,196082.09,291443.579
5,000906.SH,600518.SH,2007-04-20,0.100,26.00,27.28,25.55,26.70,25.12,1.58,6.2900,77031.91,201824.855
6,000906.SH,600770.SH,2007-04-20,0.100,21.48,23.05,21.10,23.05,20.95,2.10,10.0200,144041.16,321930.206
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995995,000906.SH,002299.SZ,2024-05-24,0.047,16.85,17.26,16.80,16.95,16.91,0.04,0.2365,91127.88,155596.610
4995996,000906.SH,000636.SZ,2024-05-24,0.047,12.22,12.30,11.85,11.86,12.24,-0.38,-3.1046,108537.00,130448.088
4995997,000906.SH,002240.SZ,2024-05-24,0.047,16.31,16.73,16.31,16.40,16.37,0.03,0.1833,109031.94,179712.332
4995998,000906.SH,600380.SH,2024-05-24,0.046,12.55,12.74,12.54,12.61,12.56,0.05,0.3981,105867.81,133986.302
4995999,000906.SH,600519.SH,2024-05-24,4.331,1693.00,1695.00,1677.00,1677.08,1692.01,-14.93,-0.8824,20216.63,3401323.915

In [ ]:
    def get_st_date(self,code):
        st_df = self.pro.namechange(ts_code=code, fields='ts_code,name,start_date,end_date,change_reason')
        st_df['start_date'] = pd.to_datetime(st_df['start_date'], format='%Y%m%d')
        st_df['end_date'] = pd.to_datetime(st_df['end_date'], format='%Y%m%d', errors='coerce')
        st_df = st_df.sort_values(by='start_date')

        # 补全结束日期
        for i in range(len(st_df) - 1):
            if pd.isna(st_df.iloc[i]['end_date']):
                st_df.iloc[i, st_df.columns.get_loc('end_date')] = st_df.iloc[i + 1]['start_date']

        # 筛选包含"ST"的行
        st_df = st_df[st_df['name'].str.contains('ST')]

        # 初始化时间列表
        time_periods = []

        # 遍历包含ST的行，收集时间段
        for index, row in st_df.iterrows():
            start_date = row['start_date']
            end_date = row['end_date'] if not pd.isna(row['end_date']) else pd.to_datetime('now')
            time_periods.append((start_date, end_date))
        return time_periods

    def get_df_st(self,df):
        flag=True
        df.sort_values(['ts_code', 'trade_date'], inplace=True)
        df.reset_index(drop=True, inplace=True)
        for code, group in tqdm(df.groupby('ts_code')):
            time_periods = self.get_st_date(code)
            # 转换 trade_date 列为 datetime 类型
            group.loc[:, 'trade_date'] = pd.to_datetime(group['trade_date'], format='%Y%m%d')

            # 初始化 is_st 列
            group.loc[:, 'is_st'] = 0  # 使用 .loc 确保操作的是原始数据

            # 检查每个交易日是否在任何ST时间段内
            for start, end in time_periods:
                idx = group[(group['trade_date'] >= start) & (group['trade_date'] <= end)].index
                # 直接在原始 df 上修改
                df.loc[idx, 'is_st'] = 1
                if len(idx) != 0 :
                    flag = False
                if not flag:
                    break
            time.sleep(0.13)

        return df